apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: "user"
  version: "default"
  importDerivedRoles:
    - user_roles
  constants:
    local:
      corporate_network_ip_range: 10.20.0.0/16
      path: /api/*/authentication/users
  rules:
    - actions: ['update']
      effect: EFFECT_ALLOW
      derivedRoles:
        - owner

    - actions: ['view']
      effect: EFFECT_ALLOW
      roles:
        - user
      condition:
        match:
          expr: request.resource.attr.imgay == false

    - actions: ['*']
      effect: EFFECT_ALLOW
      roles:
        - admin