version: '3.8'

networks:
  chatter-net:
    name: chatter-net
    driver: bridge

services:
  authentication-redis-chatter:
      image: redis:7
      container_name: authentication-redis-chatter
      restart: always
      ports:
        - "6387:6387"
      volumes:
        - ./docker/redis/data:/data
        - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf --port 6387 --appendonly yes
      networks:
        - chatter-net

  authentication-postgresql-chatter:
    image: postgres:15
    container_name: authentication-postgresql-chatter
    restart: always
    environment:
      POSTGRES_DB: chatter
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5440:5440"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "port=5440"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - chatter-net